### ISSUE TITLE
Can I summarize general deep learning papers

### ISSUE THREAD

**Issue by AnanyaP-WDW** [dair-ai/nlp_paper_summaries#42]
Hi, 
@omarsar as the title suggests would it be possible to include summaries of seminal DL papers like https://arxiv.org/abs/1611.03530. If yes then kindly allow me to work on it.
Thanks

**Comment by omarsar** [comment]
This is a great paper. Please go ahead and work on it. Remember to join our Slack group to receive support and guidance on how to publish. Thanks.

**Comment by AnanyaP-WDW** [comment]
Please review my pull request https://github.com/dair-ai/nlp_paper_summaries/pull/43
I have added the TL;DR for the paper. Presently, I am working on writing the summary.
Is it alright if I post my summary on medium and provide it's link here?

**Comment by skeshaw** [comment]
Hi Ananya.
Since you are already using Medium, you could share a draft of your article on the #editors Slack channel. That way it will be easier to pick it up for review and it can be directly added to the Medium publication as well. Of course, you can add a copy here afterwards so that it is published on the main website as well. Let us know here or in the channel if there are any queries.
Thanks.

**Comment by AnanyaP-WDW** [comment]
Sure. I will share the draft on the editors channel within a couple of days. I think it will be a good idea to directly add it to Medium afterwards. 
Thanks.
